### PR TITLE
Add provider specific column types

### LINKED ISSUE #7: Fails to insert jsonb values in Postgres
We have a table with a field of type `jsonb`, which becomes `string` in the generated type, but it doesn't seem to work when inserting a string with the json format, the exception I get is:
```
Npgsql.PostgresException (0x80004005): 42804: column "test" is of type jsonb but expression is of type text
Exception data:
    Severity: ERROR
    SqlState: 42804
    MessageText: column "test" is of type jsonb but expression is of type text
    Hint: You will need to rewrite or cast the expression.
    Position: 97
    File: parse_target.c
    Line: 588
    Routine: transformAssignedExpr
```
when trying to insert `"""{"publisher": "test"}"""`.
Would you be able to help with this?

### PR DESCRIPTION
**Pull request by MargaretKrutikova**
This PR attempts to fix #7 by adding a new attribute for fields that require db provider-specific type to be set on the corresponding command parameter. E.g. `postgres` requires `NpgsqlDbType.Json` and `NpgsqlDbType.Jsonb` to be set on the command parameter for columns of types `json` and `jsonb` correspondingly when using `Npgsql` data provider.

I am planning to add tests for the functionality after the initial review, and when I figure out how to add a new `json` column to the existing database used in tests 😄

### CODE REVIEW

**Comment by MargaretKrutikova** [comment]
Was away for a couple of days 🙂 Just ran the tests and all of them passed. Will you be able to review the code one last final time? I saw there was another PR fixing the order of the columns, but I think it is only for `SqlServer`, and I only touched `Npgsql`.

**Comment by JordanMarr** [comment]
For some reason it is not adding the new table in postgres. I think it may have something to do with with the files on the local volume not be removed, so I tried `docker-compose down -v` to remove them but no luck.
Do you have any ideas?

**Comment by MargaretKrutikova** [comment]
I think I had to remove and re-create `postgres` service from `docker`. You can also try and run `docker-compose up --build --force-recreate --no-deps -d postgresql` to just demolish the service all together and rebuild it 🙂

**Comment by JordanMarr** [comment]
Fantastic work, Margarita. Thank you! 🎉

**Comment by MargaretKrutikova** [comment]
Thanks a lot for your help! 😄

**Pull request merged**
