### PR TITLE
Add views in postgres, fix tests

### LINKED ISSUE #16: Types for views are not generated
We are using a `postgres` database and it seems like `sqlhydra` doesn't generate types for views. 
Is there anything extra we need to add in the configuration file? Or is it not supported by the library?

Thanks!

### PR DESCRIPTION
**Pull request by MargaretKrutikova**
This PR adds metadata for views in `postgres`. Fixes #16

### CODE REVIEW

**Comment by MargaretKrutikova** [comment]
I have one test that doesn't pass, `Verify Generated Code` in `Generation`. Is it like a snapshot that needs to be updated every time you change type generation?

**Comment by JordanMarr** [comment]
Awesome! That was fast 😃

**Comment by MargaretKrutikova** [comment]
What about the test? How do we fix it? 🙂

**Comment by JordanMarr** [comment]
Fixing now -- the ".verified" file has to match the resulting ".recieved" file. (Installing the Verify "DiffEngineTray" tool is the easiest way to do it.)

**Comment by JordanMarr** [comment]
Filtering it (just for fun)

**Comment by JordanMarr** [comment]
Ugh.. not as much fun as I thought (Verify was not working properly but I don't feel like filing a bug ATM).
v0.610.1 is uploading to NuGet now (I upped the revision only to avoid having to make new packages for everything else).

Thanks! 🎉

**Comment by MargaretKrutikova** [comment]
Thank you! You are awesome! 🥳

**Pull request merged**
